name: flutter_file_preview
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/opiyodon/flutter_file_preview

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.zzaning.flutter_file_preview
        pluginClass: FlutterFilePreviewPlugin
      ios:
        pluginClass: FlutterFilePreviewPlugin

  assets:
    - assets/images/ic_back.png